Issue 4332
ORNL-AMO/AMO-Tools-Desktop pull request #4367
Opened 2021-03-15 14:47 UTC by rahuldino

connects #4332 

Added new validation for the fan assessment, field data section and removed other fields.

2021-03-15 15:39 UTC, rmroot requested changes
1- The greater than and less than warnings checks for inlet pressure and outlet pressure should be a part of the checkFieldDataWarnings call and FanFieldDataWarnings object.


2- Since OutletPressure > InletPressure is an ERROR it should be apart of the form. 

In fan-field-data.service.ts getFormFromObj():

outletPressure: [obj.outletPressure, [Validators.required, Validators.min(obj.inletPressure)]`

IMPORTANT: When the inletPressure in the form changes you will need to update the validators on the form in the component. Ask me if you need help doing this.

2021-03-15 15:39 UTC, rmroot commented on src/app/fsat/fan-field-data/fan-field-data.component.html
> +          (focus)="focusField('outletPressure')" onfocus="this.select();" [readonly]="!selected" (input)="compareValues()">
Can't have two bindings to (input) event on the input element

2021-03-15 15:39 UTC, rmroot commented on src/app/fsat/fan-field-data/fan-field-data.component.html
> +        <span class="alert-warning pull-right small"
alert-warning should be used with a warning and not invalid

2021-03-15 15:39 UTC, rmroot commented on src/app/fsat/fan-field-data/fan-field-data.component.html
> +        <div *ngIf="compareError">
this should be a part of the form validation. Should be an error on outletPressure

2021-03-15 15:39 UTC, rmroot commented on src/app/fsat/fan-field-data/fan-field-data.component.ts
> +  compareValues() {
This is an error on the form and should mark the form invalid.

2021-03-15 15:39 UTC, rmroot commented on src/app/fsat/fan-field-data/fan-field-data.service.ts
> +      flowRate: [obj.flowRate, [Validators.required, Validators.min(0.1)]],
Use GreaterThanValidator

GreaterThanValidator.greaterThan(0)

2021-03-15 15:39 UTC, rmroot commented on src/app/fsat/fsat-fluid/fsat-fluid.component.html
> +      *ngIf="!gasDensityForm.controls.gasType.value == 'OTHER' || !gasDensityForm.controls.gasType.value == 'AIR'"
should be

`*ngIf="gasDensityForm.controls.gasType.value != 'OTHER'"`

2021-03-15 15:39 UTC, rmroot commented on src/app/fsat/fsat.service.ts
> -import { ConvertFanAnalysisService } from '../calculator/fans/fan-analysis/convert-fan-analysis.service';
We don't want to remove all the conversion logic...

2021-03-15 15:39 UTC, rmroot commented on src/app/fsat/fsat.service.ts
> -    inputCpy = this.convertFanAnalysisService.convertFan203DataForCalculations(inputCpy, settings);
Still need all this conversion logic in all of these places...

2021-03-16 19:01 UTC, rmroot requested changes

2021-03-16 19:01 UTC, rmroot commented on src/app/fsat/fsat-fluid/fsat-fluid.component.html
>        [ngClass]="{'indicate-different': isSpecificGravityDifferent(), 'invalid':gasDensityForm.controls.specificGravity.invalid}">
Shouldn't have the check for AIR. We want to display this field if AIR is selected

2021-03-17 10:38 UTC, nbintertech approved these changes

2021-03-17 13:44 UTC, rmroot approved these changes

2021-03-17 13:44 UTC, merged