Issue 4444
ORNL-AMO/AMO-Tools-Desktop pull request #4448
Opened 2021-04-14 13:00 UTC by nbintertech

connects #4444 

- Adding flue gas to Treasure Hunt
- Bug fix for displayed minimum temp when in metric

2021-04-16 18:19 UTC, rmroot requested changes
Need to update import-opportunities.service.ts with flue gas (looks like export is there).

Test it by exporting your data from the treasure chest, creating a new treasure hunt and importing these opportunities

2021-04-16 18:19 UTC, rmroot commented on src/app/treasure-hunt/convert-input-data.service.ts
> +        flueGas.modification.flueGasByVolume = this.convertFlueGasInput(flueGas.modification.flueGasByVolume, oldSettings);
I think this is a problem in the other areas but it's not guranteed a modification exists. Should add a check for all

2021-04-16 18:19 UTC, rmroot commented on src/app/treasure-hunt/convert-input-data.service.ts
> +      flueGasInput.combustionAirTemperature = this.convertUnitsService.value(flueGasInput.combustionAirTemperature).from('F').to('C');
use the conversion functions at the bottom convertTemperatureValue(...)

2021-04-28 12:13 UTC, nbintertech commented
Closing for new branch after large TH changes

2021-04-28 12:13 UTC, closed without merging