Added Excel import for Traverse Holes
ORNL-AMO/AMO-Tools-Desktop pull request #4622
Opened 2021-07-08 17:45 UTC by shivasaurus

Connects #4514

2021-07-08 19:11 UTC, nbintertech requested changes
Nice work here. If you haven't already, also send Kristina a screen of the page. We may want more visual division from the rest of the form. You'll want to match the font size as well

2021-07-08 19:11 UTC, nbintertech commented on src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/pressure-readings-form/pressure-readings-form.component.ts
> +          /* read workbook */
- Use let instead of var
- Remove commented ifelse block
- Comment (or rename) what we're matching in ln 100 regex

2021-07-12 20:57 UTC, rmroot approved these changes

2021-07-12 21:04 UTC, nbintertech approved these changes

2021-07-12 21:04 UTC, merged