Issue 4581 - Resolves Pump Achievable Efficiency Help Display Issue
ORNL-AMO/AMO-Tools-Desktop pull request #4662
Opened 2021-07-20 13:54 UTC by c-merchant

2021-07-20 19:59 UTC, nbintertech requested changes

2021-07-20 19:59 UTC, nbintertech commented on package.json
> +    "electron": "6.1.7",
You'll need to remove this change, as it's Mac specific. There is a way to do this through a git exlude file besides gitignore, but just manually discard the changes for now.

2021-07-20 19:59 UTC, nbintertech commented on src/app/phast/losses/operations/operations-form/operations-form.component.html
> +<div bsModal #operatingCostsModal="bs-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="operatingCostsLabel"
These changes shouldn't be part of this PR. Also if you haven't yet, switch to using VS code as your editor so you can have better management/visual on your git changes. See me if you have questions.

2021-07-21 14:33 UTC, c-merchant reviewed
Files have been changed accordingly

2021-07-22 16:02 UTC, nbintertech approved these changes

2021-07-22 16:02 UTC, merged