allowed lines and markers in data explorer scatterplot
ORNL-AMO/AMO-Tools-Desktop pull request #4668
Opened 2021-07-20 21:43 UTC by shivasaurus

Connects #3774

2021-07-21 15:37 UTC, rmroot requested changes

2021-07-21 15:37 UTC, rmroot commented on src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.ts
> +    this.markerTypes = ["lines+markers", "lines", "markers"];
for markerTypes do a type of {label: string, value: string} and capitalize the label for display.

2021-07-21 15:37 UTC, rmroot commented on src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.html
> +            <option *ngFor="let markerTypeValue of markerTypes" [ngValue]="markerTypeValue">{{markerTypeValue}}
Put this in it's own "form-group pt-2" div

2021-07-21 15:38 UTC, rmroot commented on src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.ts
> +    this.markerTypes = ["lines+markers", "lines", "markers"];
this.markerTypes = [{label: "Lines & Markers", value: "lines+markers"}]

2021-07-21 17:11 UTC, shivasaurus commented
Suggested fixes have been made.

2021-07-22 14:41 UTC, rmroot approved these changes

2021-07-22 14:41 UTC, merged