Issue 4853: Charge Material and Flue gas 'Select Type' Dropdowns bugs
ORNL-AMO/AMO-Tools-Desktop pull request #4906
Opened 2021-09-28 21:10 UTC by rhernandez-intertech

connects #4853

2021-09-29 17:57 UTC, rhernandez-intertech commented
In Charge Material and Flue Gas in the PHAST an Expression-Changed-After-It-Has-Been-Checked error would occur when the material type changed from the "select type" drop down.
I am not sure what was causing the bug, other than something wasn't being rechecked after the material type changed. 
To fix the bug I implemented cd.detectChanges() in ngOnInit() and in changeField()

2021-09-29 18:15 UTC, rmroot requested changes
It looks like adding the saveLosses() to the select dropdown is what fixed the issue. the added cd calls in this case isn't doing anything to solve the problem so it can be removed. I was unable to re-create the same bug in flue gas so it can also be removed there.

2021-09-29 18:15 UTC, rmroot commented on src/app/phast/losses/charge-material/charge-material.component.html
> +      [isBaseline]="isBaseline" (saveEmit)="saveLosses()" [lossIndex]="lossIndex" [settings]="settings" (inputError)="setError($event)"
there is no inputError event emitter in the Gas Charge Material component

2021-10-01 18:24 UTC, rmroot approved these changes

2021-10-01 18:24 UTC, merged