Added CO2Emission Results
ORNL-AMO/AMO-Tools-Desktop pull request #5139
Opened 2021-11-30 18:50 UTC by DePauwJosh

connects #4962

2021-12-01 14:08 UTC, nbintertech commented
Co2 savings results aren't working in results panel and report - also has an error. Co2Savings data are also not saving state in setup or assessment. Let me know when the functionality is good to go and I'll review

2021-12-08 22:26 UTC, rmroot requested changes

2021-12-08 22:26 UTC, rmroot commented on src/app/fsat/fsat-report/results-summary/results-summary.component.html
> +            {{modification.fsat.outputs.annualSavings | sigFigs:'3'}}</span>
This should be emissions savings not annual savings..

baseline co2 emissions - modificaiton co2 emissions

2021-12-08 22:26 UTC, rmroot commented on src/app/fsat/explore-opportunities/explore-opportunities.component.ts
> +  co2EmissionsSavings: number = 0;
unused remove

2021-12-08 22:26 UTC, rmroot commented on src/app/fsat/fsat-report/fsat-report.component.ts
> +  co2EmissionsSavings: number = 0;
unused remove

2021-12-08 22:26 UTC, rmroot commented on src/app/fsat/fsat-report/fsat-report.component.ts
> +  co2EmissionsSavings: number = 0;
also remove unused added imports

2021-12-08 22:26 UTC, rmroot commented on src/app/fsat/fsat-report/results-summary/results-summary.component.html
> +      You'll need to set these values in the fsat-report since there's no get diff here-->
Should remove comments

2021-12-08 22:26 UTC, rmroot commented on src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.ts
> +  percentSavings: number = 0;
remove unused code in this component as well

2021-12-08 22:26 UTC, rmroot commented on src/app/fsat/fsat.service.ts
> +  fsatInputs: FsatInput;
cleanup unused additions in this service

2021-12-08 22:26 UTC, rmroot commented on src/app/fsat/operations/operations.component.ts
> +  fsatInputs: FsatInput;
unused remove

2021-12-08 22:26 UTC, rmroot commented on src/app/fsat/operations/operations.service.ts
> +  // getFsatInputsFromForm(form: FormGroup, fsatInputs: FsatInput): FsatInput {
remove commented code

2021-12-08 22:26 UTC, rmroot commented on src/app/shared/models/fans.ts
> +  input?: FsatInput;
remove input addition

2021-12-13 17:30 UTC, rmroot requested changes

2021-12-13 17:30 UTC, rmroot commented on src/app/fsat/fsat.service.ts
> +    let co2EmissionsOutput: number;
unused

2021-12-13 17:30 UTC, rmroot commented on src/app/fsat/operations/operations.component.ts
> +      this.setCo2SavingsData();
Don't want to call `setCo2SavingsDate()` twice. Just keep the second one

2021-12-13 17:30 UTC, rmroot commented on src/app/shared/models/fans.ts
> +  cO2SavingsData?: Co2SavingsData;
don't need `cO2SavingsData` on `FsatInput` object

2021-12-13 17:30 UTC, rmroot commented on src/app/shared/models/fans.ts
> +export interface ExploreOpportunitiesResults {
This interface is unused. Remove

2021-12-13 18:41 UTC, rmroot approved these changes

2021-12-13 18:41 UTC, merged