Issue 4648
ORNL-AMO/AMO-Tools-Desktop pull request #5373
Opened 2022-02-23 19:07 UTC by rmroot

connects #4648 

updates to compressed air payback period table from feedback

graphs already added

2022-02-24 14:22 UTC, nbintertech requested changes

2022-02-24 14:22 UTC, nbintertech commented on src/app/compressed-air-assessment/compressed-air-report/payback-period/payback-period.component.html
> +                            {{-result.combinedResults.auxiliaryPowerUsage.cost | number:'1.0-0'}}
Intentional negative before result?

2022-02-24 21:14 UTC, rmroot commented on src/app/compressed-air-assessment/compressed-air-report/payback-period/payback-period.component.html
> +                            {{-result.combinedResults.auxiliaryPowerUsage.cost | number:'1.0-0'}}
yes

2022-02-25 13:56 UTC, nbintertech approved these changes

2022-02-25 13:56 UTC, merged