Issue 5436 - WW Influent CBOD5 help text
ORNL-AMO/AMO-Tools-Desktop pull request #5526
Opened 2022-04-07 18:29 UTC by ysintertech

connects #5436

2022-04-13 11:23 UTC, nbintertech commented
Github isn't allowing file upload right now, msg me if you need reference...

The validation error border style needs some work and the result should show a dash if it has no value. The tab button style has been changed so it's completely white when active - that may have been introduced elsewhere, but check it out please.

2022-04-13 11:23 UTC, nbintertech commented
Github isn't allowing file upload right now, msg me if you need reference...

The validation error border style needs some work and the result should show a dash if it has no value. The tab button style has been changed so it's completely white when active - that may have been introduced elsewhere, but check it out please.

2022-04-13 11:25 UTC, nbintertech requested changes

2022-04-13 11:25 UTC, nbintertech commented on src/app/shared/models/waste-water.ts
> +    isUserDefinedSo: boolean,
Test these fields with an old assessment, and update update-data.service if necessary. isUserDefinedSo may come up undefined/false and show invalid even if they had a value previously

2022-04-14 17:44 UTC, ysintertech commented
created separate issue for the whiteout styling bug #5536

2022-04-19 11:00 UTC, nbintertech requested changes

2022-04-19 11:00 UTC, nbintertech commented on src/app/waste-water/activated-sludge-form/activated-sludge-form.component.html
> +            <label>Influent CBOD<sub>5</sub> Before</label>
The two new fields still don't use disabled styling (greyed out) when they aren't selected. Use the [readonly]="!selected" like the other fields on this form

2022-04-19 16:03 UTC, nbintertech approved these changes

2022-04-19 16:03 UTC, merged