Issue 5310 - CA Assessment and Rollup Printing
ORNL-AMO/AMO-Tools-Desktop pull request #5558
Opened 2022-04-28 21:53 UTC by ysintertech

connects #5310

2022-04-28 21:55 UTC, ysintertech commented
The system profiles table _**is**_ currently being cut off, however, that will be handled in its own separate issue. This PR is merely fixing all of the issues with System Profiles graphs, Performance Profiles graph, removes scroll bars from print view, and prevents inventory data from being split in print view.

2022-05-02 10:58 UTC, nbintertech requested changes

2022-05-02 10:58 UTC, nbintertech commented on src/app/compressed-air-assessment/system-profile-graphs/system-profile-graphs.component.ts
> +      let xRangeMax: number = this.profileSummary[0].profileSummaryData.length > 1 ? 25 : 1;
We shouldn't change any of the range values for the charts unless approved by Kristina/CA team. I think we might have tried to add a padded axis like this when it was created, and they preferred it without.

Another option: in non-print view display the charts with the original axis. When in print view assign the print view values from an object.

2022-05-02 14:16 UTC, nbintertech approved these changes

2022-05-02 14:16 UTC, merged