#5532 Custom material imports
ORNL-AMO/AMO-Tools-Desktop pull request #5682
Opened 2022-06-15 17:34 UTC by JL102

connects #5532

2022-06-17 10:28 UTC, nbintertech requested changes
The current changes fix issue point 1, but the behavior from the 2nd point still persists.

2022-06-22 15:58 UTC, nbintertech commented
Still able to reproduce the 2nd point. More specific repro steps --> use a custom filename that does not have the '.json' extension. If you want reference, an implementation that guards against this is already implemented in a few other areas, i.e. exporting an assessment.

2022-06-22 19:55 UTC, JL102 commented
As discussed offline, the agreed-upon resolution to issue #2) will be to emphasize the file type in the export button ("Export as .json") to keep consistency with the export assessments screen. That way, users shouldn't be confused if they change the exported file extension and wonder why it's not importing.

I wanted to modularize the import/export modal dialog components so that the materials & assessment guys use shared code, but it would take more time than originally expected. We can put that into a new issue if desired.

2022-06-28 11:07 UTC, nbintertech approved these changes

2022-06-28 11:07 UTC, merged