Retrofit FSAT/PSAT sankeys #5146
ORNL-AMO/AMO-Tools-Desktop pull request #5711
Opened 2022-06-21 14:47 UTC by JL102

Connects #5146 
(See notes on the aforementioned issue for details)

2022-06-22 16:34 UTC, nbintertech requested changes

2022-06-22 20:36 UTC, JL102 commented on src/app/app.component.ts
> +  changeDetection: ChangeDetectionStrategy.OnPush
1. Done (8cfbdcd)
2. The Modification List was the main cause for the lag as seen in https://github.com/ORNL-AMO/AMO-Tools-Desktop/issues/5146#issuecomment-1160844952. Whenever a change is detected, the ModificationList does a **TON** of recalculations. 
`modListOpen` was already implemented in SSMT, which probably led to its lack of lag. By combining `changeDetection: ChangeDetectionStrategy.OnPush` and disabling the ModificationList when it's not visible, general assessment performance is significantly improved.

2022-06-28 15:17 UTC, nbintertech requested changes
I don't believe the openModList bools are needed. That modification list component shouldn't have an effect on sankey rendering. The component will be alive but won't be visible when the sankey component exists/is visible.

2022-06-28 19:56 UTC, nbintertech commented
- With "Let's change to OnPush for the sankey components (PHAST, FSAT, PSAT, SSMT) only." I meant the **sankey components** that correspond to each of the assessment types in the parens. I.e. <app-fsat-sankey>, <app-psat-sankey> etc.
Sorry for not being more clear there.
- Since you're going back to make changes, use the isModalOpen property if it exists instead of modListOpen

2022-07-08 18:24 UTC, nbintertech approved these changes

2022-07-08 18:25 UTC, merged