Issue 6169 - Show sidebar in every view
ORNL-AMO/AMO-Tools-Desktop pull request #6194
Opened 2023-02-13 15:02 UTC by nbintertech

#6169 

Largely stylistic changes to allow sidebar to work in every view
- a little bit of footer jump when header height changes but this is smoothed out quite a bit in the production build

2023-02-16 17:38 UTC, rmroot requested changes
![image](https://user-images.githubusercontent.com/10789740/219444494-09466d03-b870-42ec-8b94-a4b2b37b800c.png)

Looks like this screen still needs to be addressed.

2023-02-16 17:38 UTC, rmroot commented on src/app/dashboard/dashboard.component.ts
> +    this.showPrintViewSub = this.printOptionsMenuService.showPrintView.subscribe(val => {
needs type and unsubscribe 😆

2023-02-17 12:38 UTC, nbintertech commented
Updated - if you've got any ideas as to why TH welcome-screen would need different styling vs say fsat welcome-screen considering they both have the same layout, css, and are top level components at the router-outlet... please do let me know so I can sleep this weekend.

The borders are like that in dev. I backlogged 6202 for that and more welcome-screen tightening

2023-02-20 19:29 UTC, rmroot approved these changes

2023-02-20 20:29 UTC, merged