Issue 6131 - Save annotations in memory
ORNL-AMO/AMO-Tools-Desktop pull request #6228
Opened 2023-04-11 11:19 UTC by nbintertech

#6131 

- Keeping comments with context/reasons why
- This needs #6225 to work with time segments

2023-04-12 17:17 UTC, rhernandez-intertech requested changes
Annotations are not being saved when switching from graph to graph. When Y axis changes annotations do not reset

2023-04-12 17:18 UTC, rhernandez-intertech commented
Next button disabled even after data is uploaded
![image](https://user-images.githubusercontent.com/84926132/231534129-c1837b41-37d8-4e9a-8557-3f70bc0e973a.png)

2023-04-12 18:58 UTC, nbintertech commented
> Next button disabled even after data is uploaded 
The changes in this PR shouldn't have sideffects on that logic. I think what you saw it probably #6177

2023-04-13 18:53 UTC, rhernandez-intertech approved these changes

2023-04-13 18:53 UTC, merged