file name is changed whenever exporting a single assessment
ORNL-AMO/AMO-Tools-Desktop pull request #6268
Opened 2023-06-01 19:28 UTC by kaichen127

connects #5645

2023-06-02 21:54 UTC, rhernandez-intertech requested changes

2023-06-02 21:54 UTC, rhernandez-intertech commented on src/app/dashboard/import-export/export-modal/export-modal.component.ts
> +    if (this.noDirectoryAssessments.length == 1 && this.exportData.directories.length == 0) {
you're on the right track with this solution, but when a just a folder is selected to be exported then name defaults to the name of the folder the selected folder is in when it should default to the name of the selected folder.

2023-06-08 14:56 UTC, nbintertech requested changes

2023-06-08 14:56 UTC, nbintertech commented on src/app/dashboard/import-export/export-modal/export-modal.component.ts
> +  directory: Directory;
I don't think directory needs to be a class property - can keep original "let directory.."

2023-06-08 14:56 UTC, nbintertech commented on src/app/dashboard/import-export/export-modal/export-modal.component.ts
> +  // can change method name to be more specific since we're not ONLY exporting DIR data
Please remove my previous comments

2023-06-08 15:26 UTC, nbintertech approved these changes

2023-06-08 15:27 UTC, merged