Issue 6202:  the overlay seems to have a max width and will run short on larger screens. Can we make it so that "overlay" is right justified and the excess space is covered in the black?
ORNL-AMO/AMO-Tools-Desktop pull request #6344
Opened 2023-06-28 15:43 UTC by kaichen127

Connects #6202

2023-06-28 19:39 UTC, rhernandez-intertech approved these changes

2023-06-28 20:15 UTC, rhernandez-intertech approved these changes

2023-06-30 11:35 UTC, nbintertech requested changes

2023-06-30 11:35 UTC, nbintertech commented on src/app/compressed-air-assessment/welcome-screen/welcome-screen.component.html
> +                <a class="user-manual" href="assets/user-manuals/Compressed-Air-User-Manual.pdf" target="_blank" style = "right: 300px;">
Use a css class please

2023-06-30 18:19 UTC, nbintertech approved these changes

2023-06-30 18:19 UTC, merged