Issue 6355: Arrow key - Process Heating Fuel Fired
ORNL-AMO/AMO-Tools-Desktop pull request #6401
Opened 2023-07-25 13:22 UTC by kaichen127

Connects #6355 

(also changed all instances of capital SCF to lowercase scf - might have changed some variable names too in the typescript but I separated them via commits)

2023-07-25 18:09 UTC, rhernandez-intertech requested changes
Looking good, just a few were missed/needs correction: 
- Charge Materials - solid - Heat of Reaction needs to have a step of 10
- Flue Gas - solid/liquid - Ash Temperature step should be 10
- Other - Loss Description needs step of 10
- Auxiliary Power - Voltage step needs step of 10
- Auxiliary Power - Power Factor step needs step of 0.1
- Metered Energy - Fuel - Heating Value HHV needs step of 100

2023-07-25 20:49 UTC, rhernandez-intertech requested changes
Other loss Loss Description still needs a step of 10
![image](https://github.com/ORNL-AMO/AMO-Tools-Desktop/assets/84926132/84a2384d-8959-4cd8-ae2e-e9c4d6e5a6cf)

Metered Energy Heating Value HHV needs step of 100
![image](https://github.com/ORNL-AMO/AMO-Tools-Desktop/assets/84926132/d8843e0a-9b61-41e0-b2e0-f4d52b9f92ec)

2023-07-26 18:20 UTC, rhernandez-intertech approved these changes

2023-07-26 19:25 UTC, nbintertech requested changes
There needs to be something in this issue and PR describing the scope of the unit changes here. This is a pretty widesweeping change that I don't see any requirements on - other than the unit label noted by Kristina. 

We'd normally put something like this in it's own issue since it's not related to number input steps, but since this is pretty big don't worry about pulling it out.

2023-07-28 16:56 UTC, nbintertech approved these changes

2023-07-28 16:57 UTC, merged